version: '3.8'
services:
  web:
    tty: true
    stdin_open: true
    build: .
    command: rails s -b 0.0.0.0
    volumes:
      - .:/app
    environment:
      EDITOR: vim
    ports:
      - "3002:3000"
